DROP TABLE IF EXISTS node;
CREATE TABLE IF NOT EXISTS node (
	id INTEGER,
	code TEXT,
	label TEXT,
	CONSTRAINT node_PK PRIMARY KEY (id)
);

DROP TABLE IF EXISTS edge;
CREATE TABLE IF NOT EXISTS edge (
	id INTEGER,
	source_node_id INTEGER,
	target_node_id INTEGER,
	label TEXT,
	CONSTRAINT edge_PK PRIMARY KEY (id),
	CONSTRAINT edge_source_FK FOREIGN KEY (source_node_id) REFERENCES node(id),
	CONSTRAINT edge_target_FK FOREIGN KEY (target_node_id) REFERENCES node(id)
);

INSERT INTO node (id, code, label) VALUES(0, 'GS:14c', '🚩 14c');
INSERT INTO node (id, code, label) VALUES(1, 'S:011', '⚔ #011');
INSERT INTO node (id, code, label) VALUES(2, 'GS:15q', '🚩 15q');
INSERT INTO node (id, code, label) VALUES(3, 'GS:R-13', '🚩 R-13');
INSERT INTO node (id, code, label) VALUES(4, 'GS:END-I', '🚩 END-I');
INSERT INTO node (id, code, label) VALUES(5, 'GS:14d', '🚩 14d');
INSERT INTO node (id, code, label) VALUES(6, 'GS:12h', '🚩 12h');
INSERT INTO node (id, code, label) VALUES(7, 'GS:END-G', '🚩 END-G');
INSERT INTO node (id, code, label) VALUES(8, 'GS:2b', '🚩 2b');
INSERT INTO node (id, code, label) VALUES(9, 'B:252', '💬 252');
INSERT INTO node (id, code, label) VALUES(10, 'GS:13k', '🚩 13k');
INSERT INTO node (id, code, label) VALUES(11, 'GS:14o', '🚩 14o');
INSERT INTO node (id, code, label) VALUES(12, 'B:073', '💬 073');
INSERT INTO node (id, code, label) VALUES(13, 'GS:10n', '🚩 10n');
INSERT INTO node (id, code, label) VALUES(14, 'GS:10q', '🚩 10q');
INSERT INTO node (id, code, label) VALUES(15, 'B:208', '💬 208');
INSERT INTO node (id, code, label) VALUES(16, 'GS:15m', '🚩 15m');
INSERT INTO node (id, code, label) VALUES(17, 'GS:14b', '🚩 14b');
INSERT INTO node (id, code, label) VALUES(18, 'GS:13m', '🚩 13m');
INSERT INTO node (id, code, label) VALUES(19, 'B:214', '💬 214');
INSERT INTO node (id, code, label) VALUES(20, 'B:140', '💬 140');
INSERT INTO node (id, code, label) VALUES(21, 'GS:R-16', '🚩 R-16');
INSERT INTO node (id, code, label) VALUES(22, 'GS:8h', '🚩 8h');
INSERT INTO node (id, code, label) VALUES(23, 'GS:15f', '🚩 15f');
INSERT INTO node (id, code, label) VALUES(24, 'B:390', '💬 390');
INSERT INTO node (id, code, label) VALUES(25, 'GS:15d', '🚩 15d');
INSERT INTO node (id, code, label) VALUES(26, 'GS:7f', '🚩 7f');
INSERT INTO node (id, code, label) VALUES(27, 'GS:14h', '🚩 14h');
INSERT INTO node (id, code, label) VALUES(28, 'GS:13e', '🚩 13e');
INSERT INTO node (id, code, label) VALUES(29, 'GS:5a', '🚩 5a');
INSERT INTO node (id, code, label) VALUES(30, 'GS:R-05', '🚩 R-05');
INSERT INTO node (id, code, label) VALUES(31, 'GS:R-06', '🚩 R-06');
INSERT INTO node (id, code, label) VALUES(32, 'GS:6a', '🚩 6a');
INSERT INTO node (id, code, label) VALUES(33, 'GS:11f', '🚩 11f');
INSERT INTO node (id, code, label) VALUES(34, 'B:231', '💬 231');
INSERT INTO node (id, code, label) VALUES(35, 'GS:R-11', '🚩 R-11');
INSERT INTO node (id, code, label) VALUES(36, 'GS:4c', '🚩 4c');
INSERT INTO node (id, code, label) VALUES(37, 'GS:15a', '🚩 15a');
INSERT INTO node (id, code, label) VALUES(38, 'B:178', '💬 178');
INSERT INTO node (id, code, label) VALUES(39, 'GS:3b', '🚩 3b');
INSERT INTO node (id, code, label) VALUES(40, 'B:480', '💬 480');
INSERT INTO node (id, code, label) VALUES(41, 'GS:R-01', '🚩 R-01');
INSERT INTO node (id, code, label) VALUES(42, 'S:031', '⚔ #031');
INSERT INTO node (id, code, label) VALUES(43, 'GS:R-25', '🚩 R-25');
INSERT INTO node (id, code, label) VALUES(44, 'GS:R-08', '🚩 R-08');
INSERT INTO node (id, code, label) VALUES(45, 'B:488', '💬 488');
INSERT INTO node (id, code, label) VALUES(46, 'GS:R-21', '🚩 R-21');
INSERT INTO node (id, code, label) VALUES(47, 'B:408', '💬 408');
INSERT INTO node (id, code, label) VALUES(48, 'GS:9j', '🚩 9j');
INSERT INTO node (id, code, label) VALUES(49, 'B:269', '💬 269');
INSERT INTO node (id, code, label) VALUES(50, 'GS:END-D', '🚩 END-D');
INSERT INTO node (id, code, label) VALUES(51, 'GS:10s', '🚩 10s');
INSERT INTO node (id, code, label) VALUES(52, 'GS:14q', '🚩 14q');
INSERT INTO node (id, code, label) VALUES(53, 'GS:15h', '🚩 15h');
INSERT INTO node (id, code, label) VALUES(54, 'GS:15s', '🚩 15s');
INSERT INTO node (id, code, label) VALUES(55, 'GS:10d', '🚩 10d');
INSERT INTO node (id, code, label) VALUES(56, 'GS:R-18', '🚩 R-18');
INSERT INTO node (id, code, label) VALUES(57, 'S:143', '⚔ #143');
INSERT INTO node (id, code, label) VALUES(58, 'GS:14j', '🚩 14j');
INSERT INTO node (id, code, label) VALUES(59, 'GS:9b', '🚩 9b');
INSERT INTO node (id, code, label) VALUES(60, 'B:158', '💬 158');
INSERT INTO node (id, code, label) VALUES(61, 'B:487', '💬 487');
INSERT INTO node (id, code, label) VALUES(62, 'GS:R-26', '🚩 R-26');
INSERT INTO node (id, code, label) VALUES(63, 'GS:END-B', '🚩 END-B');
INSERT INTO node (id, code, label) VALUES(64, 'GS:12i', '🚩 12i');
INSERT INTO node (id, code, label) VALUES(65, 'GS:12c', '🚩 12c');
INSERT INTO node (id, code, label) VALUES(66, 'GS:11o', '🚩 11o');
INSERT INTO node (id, code, label) VALUES(67, 'GS:14n', '🚩 14n');
INSERT INTO node (id, code, label) VALUES(68, 'S:052', '⚔ #052');
INSERT INTO node (id, code, label) VALUES(69, 'GS:9c', '🚩 9c');
INSERT INTO node (id, code, label) VALUES(70, 'GS:9g', '🚩 9g');
INSERT INTO node (id, code, label) VALUES(71, 'B:068', '💬 068');
INSERT INTO node (id, code, label) VALUES(72, 'GS:14g', '🚩 14g');
INSERT INTO node (id, code, label) VALUES(73, 'S:054', '⚔ #054');
INSERT INTO node (id, code, label) VALUES(74, 'GS:10i', '🚩 10i');
INSERT INTO node (id, code, label) VALUES(75, 'GS:10x', '🚩 10x');
INSERT INTO node (id, code, label) VALUES(76, 'GS:END-A', '🚩 END-A');
INSERT INTO node (id, code, label) VALUES(77, 'GS:15w', '🚩 15w');
INSERT INTO node (id, code, label) VALUES(78, 'B:279', '💬 279');
INSERT INTO node (id, code, label) VALUES(79, 'GS:7g', '🚩 7g');
INSERT INTO node (id, code, label) VALUES(80, 'S:152', '⚔ #152');
INSERT INTO node (id, code, label) VALUES(81, 'GS:9m', '🚩 9m');
INSERT INTO node (id, code, label) VALUES(82, 'GS:13n', '🚩 13n');
INSERT INTO node (id, code, label) VALUES(83, 'GS:11c', '🚩 11c');
INSERT INTO node (id, code, label) VALUES(84, 'B:314', '💬 314');
INSERT INTO node (id, code, label) VALUES(85, 'GS:11k', '🚩 11k');
INSERT INTO node (id, code, label) VALUES(86, 'GS:7h', '🚩 7h');
INSERT INTO node (id, code, label) VALUES(87, 'S:122', '⚔ #122');
INSERT INTO node (id, code, label) VALUES(88, 'S:142', '⚔ #142');
INSERT INTO node (id, code, label) VALUES(89, 'GS:10f', '🚩 10f');
INSERT INTO node (id, code, label) VALUES(90, 'GS:R-03', '🚩 R-03');
INSERT INTO node (id, code, label) VALUES(91, 'GS:14aa', '🚩 14aa');
INSERT INTO node (id, code, label) VALUES(92, 'GS:8d', '🚩 8d');
INSERT INTO node (id, code, label) VALUES(93, 'GS:14f', '🚩 14f');
INSERT INTO node (id, code, label) VALUES(94, 'S:101', '⚔ #101');
INSERT INTO node (id, code, label) VALUES(95, 'GS:8f', '🚩 8f');
INSERT INTO node (id, code, label) VALUES(96, 'S:053', '⚔ #053');
INSERT INTO node (id, code, label) VALUES(97, 'S:022', '⚔ #022');
INSERT INTO node (id, code, label) VALUES(98, 'B:015', '💬 015');
INSERT INTO node (id, code, label) VALUES(99, 'GS:END-', '🚩 END-');
INSERT INTO node (id, code, label) VALUES(100, 'S:144', '⚔ #144');
INSERT INTO node (id, code, label) VALUES(101, 'GS:12f', '🚩 12f');
INSERT INTO node (id, code, label) VALUES(102, 'B:445', '💬 445');
INSERT INTO node (id, code, label) VALUES(103, 'GS:3c', '🚩 3c');
INSERT INTO node (id, code, label) VALUES(104, 'B:028', '💬 028');
INSERT INTO node (id, code, label) VALUES(105, 'B:350', '💬 350');
INSERT INTO node (id, code, label) VALUES(106, 'GS:5d', '🚩 5d');
INSERT INTO node (id, code, label) VALUES(107, 'B:104', '💬 104');
INSERT INTO node (id, code, label) VALUES(108, 'GS:8g', '🚩 8g');
INSERT INTO node (id, code, label) VALUES(109, 'GS:7a', '🚩 7a');
INSERT INTO node (id, code, label) VALUES(110, 'GS:7e', '🚩 7e');
INSERT INTO node (id, code, label) VALUES(111, 'B:079', '💬 079');
INSERT INTO node (id, code, label) VALUES(112, 'B:382', '💬 382');
INSERT INTO node (id, code, label) VALUES(113, 'B:307', '💬 307');
INSERT INTO node (id, code, label) VALUES(114, 'GS:14v', '🚩 14v');
INSERT INTO node (id, code, label) VALUES(115, 'GS:R-32', '🚩 R-32');
INSERT INTO node (id, code, label) VALUES(116, 'GS:END-M', '🚩 END-M');
INSERT INTO node (id, code, label) VALUES(117, 'GS:11i', '🚩 11i');
INSERT INTO node (id, code, label) VALUES(118, 'B:221', '💬 221');
INSERT INTO node (id, code, label) VALUES(119, 'B:204', '💬 204');
INSERT INTO node (id, code, label) VALUES(120, 'GS:R-23', '🚩 R-23');
INSERT INTO node (id, code, label) VALUES(121, 'S:071', '⚔ #071');
INSERT INTO node (id, code, label) VALUES(122, 'GS:4d', '🚩 4d');
INSERT INTO node (id, code, label) VALUES(123, 'GS:7b', '🚩 7b');
INSERT INTO node (id, code, label) VALUES(124, 'B:154', '💬 154');
INSERT INTO node (id, code, label) VALUES(125, 'B:156', '💬 156');
INSERT INTO node (id, code, label) VALUES(126, 'GS:15u', '🚩 15u');
INSERT INTO node (id, code, label) VALUES(127, 'GS:12j', '🚩 12j');
INSERT INTO node (id, code, label) VALUES(128, 'S:061', '⚔ #061');
INSERT INTO node (id, code, label) VALUES(129, 'B:032', '💬 032');
INSERT INTO node (id, code, label) VALUES(130, 'GS:15c', '🚩 15c');
INSERT INTO node (id, code, label) VALUES(131, 'S:131', '⚔ #131');
INSERT INTO node (id, code, label) VALUES(132, 'GS:12o', '🚩 12o');
INSERT INTO node (id, code, label) VALUES(133, 'B:143', '💬 143');
INSERT INTO node (id, code, label) VALUES(134, 'GS:10u', '🚩 10u');
INSERT INTO node (id, code, label) VALUES(135, 'GS:10b', '🚩 10b');
INSERT INTO node (id, code, label) VALUES(136, 'GS:14ab', '🚩 14ab');
INSERT INTO node (id, code, label) VALUES(137, 'GS:R-22', '🚩 R-22');
INSERT INTO node (id, code, label) VALUES(138, 'GS:R-29', '🚩 R-29');
INSERT INTO node (id, code, label) VALUES(139, 'GS:12m', '🚩 12m');
INSERT INTO node (id, code, label) VALUES(140, 'B:139', '💬 139');
INSERT INTO node (id, code, label) VALUES(141, 'GS:3a', '🚩 3a');
INSERT INTO node (id, code, label) VALUES(142, 'GS:11e', '🚩 11e');
INSERT INTO node (id, code, label) VALUES(143, 'B:219', '💬 219');
INSERT INTO node (id, code, label) VALUES(144, 'S:091', '⚔ #091');
INSERT INTO node (id, code, label) VALUES(145, 'B:183', '💬 183');
INSERT INTO node (id, code, label) VALUES(146, 'GS:10l', '🚩 10l');
INSERT INTO node (id, code, label) VALUES(147, 'GS:R-09', '🚩 R-09');
INSERT INTO node (id, code, label) VALUES(148, 'GS:15o', '🚩 15o');
INSERT INTO node (id, code, label) VALUES(149, 'GS:END-L', '🚩 END-L');
INSERT INTO node (id, code, label) VALUES(150, 'GS:10c', '🚩 10c');
INSERT INTO node (id, code, label) VALUES(151, 'GS:R-07', '🚩 R-07');
INSERT INTO node (id, code, label) VALUES(152, 'GS:R-30', '🚩 R-30');
INSERT INTO node (id, code, label) VALUES(153, 'GS:15b', '🚩 15b');
INSERT INTO node (id, code, label) VALUES(154, 'B:440', '💬 440');
INSERT INTO node (id, code, label) VALUES(155, 'GS:11p', '🚩 11p');
INSERT INTO node (id, code, label) VALUES(156, 'GS:END-N', '🚩 END-N');
INSERT INTO node (id, code, label) VALUES(157, 'B:242', '💬 242');
INSERT INTO node (id, code, label) VALUES(158, 'GS:7c', '🚩 7c');
INSERT INTO node (id, code, label) VALUES(159, 'GS:13g', '🚩 13g');
INSERT INTO node (id, code, label) VALUES(160, 'GS:14u', '🚩 14u');
INSERT INTO node (id, code, label) VALUES(161, 'B:490', '💬 490');
INSERT INTO node (id, code, label) VALUES(162, 'GS:14e', '🚩 14e');
INSERT INTO node (id, code, label) VALUES(163, 'GS:15l', '🚩 15l');
INSERT INTO node (id, code, label) VALUES(164, 'GS:8e', '🚩 8e');
INSERT INTO node (id, code, label) VALUES(165, 'GS:10a', '🚩 10a');
INSERT INTO node (id, code, label) VALUES(166, 'GS:10m', '🚩 10m');
INSERT INTO node (id, code, label) VALUES(167, 'GS:9l', '🚩 9l');
INSERT INTO node (id, code, label) VALUES(168, 'GS:10j', '🚩 10j');
INSERT INTO node (id, code, label) VALUES(169, 'GS:10h', '🚩 10h');
INSERT INTO node (id, code, label) VALUES(170, 'GS:9n', '🚩 9n');
INSERT INTO node (id, code, label) VALUES(171, 'S:121', '⚔ #121');
INSERT INTO node (id, code, label) VALUES(172, 'GS:11h', '🚩 11h');
INSERT INTO node (id, code, label) VALUES(173, 'GS:14z', '🚩 14z');
INSERT INTO node (id, code, label) VALUES(174, 'GS:13f', '🚩 13f');
INSERT INTO node (id, code, label) VALUES(175, 'S:042', '⚔ #042');
INSERT INTO node (id, code, label) VALUES(176, 'GS:R-19', '🚩 R-19');
INSERT INTO node (id, code, label) VALUES(177, 'S:133', '⚔ #133');
INSERT INTO node (id, code, label) VALUES(178, 'S:124', '⚔ #124');
INSERT INTO node (id, code, label) VALUES(179, 'GS:5b', '🚩 5b');
INSERT INTO node (id, code, label) VALUES(180, 'S:112', '⚔ #112');
INSERT INTO node (id, code, label) VALUES(181, 'GS:END-C', '🚩 END-C');
INSERT INTO node (id, code, label) VALUES(182, 'GS:3d', '🚩 3d');
INSERT INTO node (id, code, label) VALUES(183, 'GS:14k', '🚩 14k');
INSERT INTO node (id, code, label) VALUES(184, 'GS:9o', '🚩 9o');
INSERT INTO node (id, code, label) VALUES(185, 'B:466', '💬 466');
INSERT INTO node (id, code, label) VALUES(186, 'B:217', '💬 217');
INSERT INTO node (id, code, label) VALUES(187, 'GS:12g', '🚩 12g');
INSERT INTO node (id, code, label) VALUES(188, 'GS:14m', '🚩 14m');
INSERT INTO node (id, code, label) VALUES(189, 'B:1', '💬 1');
INSERT INTO node (id, code, label) VALUES(190, 'GS:14t', '🚩 14t');
INSERT INTO node (id, code, label) VALUES(191, 'B:038', '💬 038');
INSERT INTO node (id, code, label) VALUES(192, 'GS:11g', '🚩 11g');
INSERT INTO node (id, code, label) VALUES(193, 'GS:8b', '🚩 8b');
INSERT INTO node (id, code, label) VALUES(194, 'B:037', '💬 037');
INSERT INTO node (id, code, label) VALUES(195, 'GS:9k', '🚩 9k');
INSERT INTO node (id, code, label) VALUES(196, 'GS:15t', '🚩 15t');
INSERT INTO node (id, code, label) VALUES(197, 'GS:12e', '🚩 12e');
INSERT INTO node (id, code, label) VALUES(198, 'B:115', '💬 115');
INSERT INTO node (id, code, label) VALUES(199, 'GS:15p', '🚩 15p');
INSERT INTO node (id, code, label) VALUES(200, 'S:041', '⚔ #041');
INSERT INTO node (id, code, label) VALUES(201, 'B:463', '💬 463');
INSERT INTO node (id, code, label) VALUES(202, 'GS:8a', '🚩 8a');
INSERT INTO node (id, code, label) VALUES(203, 'B:323', '💬 323');
INSERT INTO node (id, code, label) VALUES(204, 'B:320', '💬 320');
INSERT INTO node (id, code, label) VALUES(205, 'GS:12k', '🚩 12k');
INSERT INTO node (id, code, label) VALUES(206, 'GS:13l', '🚩 13l');
INSERT INTO node (id, code, label) VALUES(207, 'B:491', '💬 491');
INSERT INTO node (id, code, label) VALUES(208, 'GS:2a', '🚩 2a');
INSERT INTO node (id, code, label) VALUES(209, 'GS:10k', '🚩 10k');
INSERT INTO node (id, code, label) VALUES(210, 'B:162', '💬 162');
INSERT INTO node (id, code, label) VALUES(211, 'GS:13c', '🚩 13c');
INSERT INTO node (id, code, label) VALUES(212, 'GS:15y', '🚩 15y');
INSERT INTO node (id, code, label) VALUES(213, 'GS:R-27', '🚩 R-27');
INSERT INTO node (id, code, label) VALUES(214, 'B:142', '💬 142');
INSERT INTO node (id, code, label) VALUES(215, 'GS:10o', '🚩 10o');
INSERT INTO node (id, code, label) VALUES(216, 'GS:13j', '🚩 13j');
INSERT INTO node (id, code, label) VALUES(217, 'GS:12d', '🚩 12d');
INSERT INTO node (id, code, label) VALUES(218, 'GS:R-10', '🚩 R-10');
INSERT INTO node (id, code, label) VALUES(219, 'GS:4a', '🚩 4a');
INSERT INTO node (id, code, label) VALUES(220, 'GS:R-02', '🚩 R-02');
INSERT INTO node (id, code, label) VALUES(221, 'GS:R-12', '🚩 R-12');
INSERT INTO node (id, code, label) VALUES(222, 'GS:15aa', '🚩 15aa');
INSERT INTO node (id, code, label) VALUES(223, 'B:108', '💬 108');
INSERT INTO node (id, code, label) VALUES(224, 'B:289', '💬 289');
INSERT INTO node (id, code, label) VALUES(225, 'B:430', '💬 430');
INSERT INTO node (id, code, label) VALUES(226, 'B:368', '💬 368');
INSERT INTO node (id, code, label) VALUES(227, 'B:270', '💬 270');
INSERT INTO node (id, code, label) VALUES(228, 'GS:14a', '🚩 14a');
INSERT INTO node (id, code, label) VALUES(229, 'GS:12n', '🚩 12n');
INSERT INTO node (id, code, label) VALUES(230, 'GS:R-31', '🚩 R-31');
INSERT INTO node (id, code, label) VALUES(231, 'S:072', '⚔ #072');
INSERT INTO node (id, code, label) VALUES(232, 'B:189', '💬 189');
INSERT INTO node (id, code, label) VALUES(233, 'GS:11m', '🚩 11m');
INSERT INTO node (id, code, label) VALUES(234, 'S:092', '⚔ #092');
INSERT INTO node (id, code, label) VALUES(235, 'GS:13b', '🚩 13b');
INSERT INTO node (id, code, label) VALUES(236, 'GS:11b', '🚩 11b');
INSERT INTO node (id, code, label) VALUES(237, 'GS:14x', '🚩 14x');
INSERT INTO node (id, code, label) VALUES(238, 'B:263', '💬 263');
INSERT INTO node (id, code, label) VALUES(239, 'GS:R-04', '🚩 R-04');
INSERT INTO node (id, code, label) VALUES(240, 'S:051', '⚔ #051');
INSERT INTO node (id, code, label) VALUES(241, 'GS:END-H', '🚩 END-H');
INSERT INTO node (id, code, label) VALUES(242, 'GS:END-E', '🚩 END-E');
INSERT INTO node (id, code, label) VALUES(243, 'GS:13o', '🚩 13o');
INSERT INTO node (id, code, label) VALUES(244, 'S:111', '⚔ #111');
INSERT INTO node (id, code, label) VALUES(245, 'B:434', '💬 434');
INSERT INTO node (id, code, label) VALUES(246, 'GS:R-15', '🚩 R-15');
INSERT INTO node (id, code, label) VALUES(247, 'GS:9a', '🚩 9a');
INSERT INTO node (id, code, label) VALUES(248, 'GS:R-28', '🚩 R-28');
INSERT INTO node (id, code, label) VALUES(249, 'GS:10e', '🚩 10e');
INSERT INTO node (id, code, label) VALUES(250, 'S:021', '⚔ #021');
INSERT INTO node (id, code, label) VALUES(251, 'GS:15n', '🚩 15n');
INSERT INTO node (id, code, label) VALUES(252, 'S:082', '⚔ #082');
INSERT INTO node (id, code, label) VALUES(253, 'GS:END-F', '🚩 END-F');
INSERT INTO node (id, code, label) VALUES(254, 'GS:R-14', '🚩 R-14');
INSERT INTO node (id, code, label) VALUES(255, 'GS:14s', '🚩 14s');
INSERT INTO node (id, code, label) VALUES(256, 'GS:11a', '🚩 11a');
INSERT INTO node (id, code, label) VALUES(257, 'B:340', '💬 340');
INSERT INTO node (id, code, label) VALUES(258, 'B:012', '💬 012');
INSERT INTO node (id, code, label) VALUES(259, 'B:023', '💬 023');
INSERT INTO node (id, code, label) VALUES(260, 'B:325', '💬 325');
INSERT INTO node (id, code, label) VALUES(261, 'GS:15e', '🚩 15e');
INSERT INTO node (id, code, label) VALUES(262, 'GS:6c', '🚩 6c');
INSERT INTO node (id, code, label) VALUES(263, 'GS:10r', '🚩 10r');
INSERT INTO node (id, code, label) VALUES(264, 'GS:12a', '🚩 12a');
INSERT INTO node (id, code, label) VALUES(265, 'GS:11j', '🚩 11j');
INSERT INTO node (id, code, label) VALUES(266, 'GS:14i', '🚩 14i');
INSERT INTO node (id, code, label) VALUES(267, 'S:081', '⚔ #081');
INSERT INTO node (id, code, label) VALUES(268, 'GS:END-K', '🚩 END-K');
INSERT INTO node (id, code, label) VALUES(269, 'B:483', '💬 483');
INSERT INTO node (id, code, label) VALUES(270, 'B:046', '💬 046');
INSERT INTO node (id, code, label) VALUES(271, 'B:361', '💬 361');
INSERT INTO node (id, code, label) VALUES(272, 'GS:1a', '🚩 1a');
INSERT INTO node (id, code, label) VALUES(273, 'S:032', '⚔ #032');
INSERT INTO node (id, code, label) VALUES(274, 'GS:9f', '🚩 9f');
INSERT INTO node (id, code, label) VALUES(275, 'GS:R-20', '🚩 R-20');
INSERT INTO node (id, code, label) VALUES(276, 'GS:8c', '🚩 8c');
INSERT INTO node (id, code, label) VALUES(277, 'GS:9d', '🚩 9d');
INSERT INTO node (id, code, label) VALUES(278, 'GS:13h', '🚩 13h');
INSERT INTO node (id, code, label) VALUES(279, 'GS:4b', '🚩 4b');
INSERT INTO node (id, code, label) VALUES(280, 'GS:14y', '🚩 14y');
INSERT INTO node (id, code, label) VALUES(281, 'B:384', '💬 384');
INSERT INTO node (id, code, label) VALUES(282, 'GS:10w', '🚩 10w');
INSERT INTO node (id, code, label) VALUES(283, 'B:245', '💬 245');
INSERT INTO node (id, code, label) VALUES(284, 'GS:R-24', '🚩 R-24');
INSERT INTO node (id, code, label) VALUES(285, 'GS:11d', '🚩 11d');
INSERT INTO node (id, code, label) VALUES(286, 'B:321', '💬 321');
INSERT INTO node (id, code, label) VALUES(287, 'GS:10g', '🚩 10g');
INSERT INTO node (id, code, label) VALUES(288, 'S:132', '⚔ #132');
INSERT INTO node (id, code, label) VALUES(289, 'GS:9e', '🚩 9e');
INSERT INTO node (id, code, label) VALUES(290, 'GS:15i', '🚩 15i');
INSERT INTO node (id, code, label) VALUES(291, 'B:405', '💬 405');
INSERT INTO node (id, code, label) VALUES(292, 'GS:13d', '🚩 13d');
INSERT INTO node (id, code, label) VALUES(293, 'GS:11l', '🚩 11l');
INSERT INTO node (id, code, label) VALUES(294, 'GS:10p', '🚩 10p');
INSERT INTO node (id, code, label) VALUES(295, 'GS:9p', '🚩 9p');
INSERT INTO node (id, code, label) VALUES(296, 'GS:10v', '🚩 10v');
INSERT INTO node (id, code, label) VALUES(297, 'GS:14r', '🚩 14r');
INSERT INTO node (id, code, label) VALUES(298, 'GS:13i', '🚩 13i');
INSERT INTO node (id, code, label) VALUES(299, 'B:413', '💬 413');
INSERT INTO node (id, code, label) VALUES(300, 'GS:END-J', '🚩 END-J');
INSERT INTO node (id, code, label) VALUES(301, 'GS:9h', '🚩 9h');
INSERT INTO node (id, code, label) VALUES(302, 'B:420', '💬 420');
INSERT INTO node (id, code, label) VALUES(303, 'GS:12p', '🚩 12p');
INSERT INTO node (id, code, label) VALUES(304, 'B:298', '💬 298');
INSERT INTO node (id, code, label) VALUES(305, 'GS:10rj', '🚩 10rj');
INSERT INTO node (id, code, label) VALUES(306, 'GS:6d', '🚩 6d');
INSERT INTO node (id, code, label) VALUES(307, 'B:109', '💬 109');
INSERT INTO node (id, code, label) VALUES(308, 'GS:10t', '🚩 10t');
INSERT INTO node (id, code, label) VALUES(309, 'GS:12l', '🚩 12l');
INSERT INTO node (id, code, label) VALUES(310, 'GS:15x', '🚩 15x');
INSERT INTO node (id, code, label) VALUES(311, 'S:151', '⚔ #151');
INSERT INTO node (id, code, label) VALUES(312, 'S:113', '⚔ #113');
INSERT INTO node (id, code, label) VALUES(313, 'B:042', '💬 042');
INSERT INTO node (id, code, label) VALUES(314, 'B:093', '💬 093');
INSERT INTO node (id, code, label) VALUES(315, 'GS:5c', '🚩 5c');
INSERT INTO node (id, code, label) VALUES(316, 'GS:14p', '🚩 14p');
INSERT INTO node (id, code, label) VALUES(317, 'S:102', '⚔ #102');
INSERT INTO node (id, code, label) VALUES(318, 'S:141', '⚔ #141');
INSERT INTO node (id, code, label) VALUES(319, 'B:165', '💬 165');
INSERT INTO node (id, code, label) VALUES(320, 'GS:12b', '🚩 12b');
INSERT INTO node (id, code, label) VALUES(321, 'GS:6b', '🚩 6b');
INSERT INTO node (id, code, label) VALUES(322, 'GS:7d', '🚩 7d');
INSERT INTO node (id, code, label) VALUES(323, 'S:123', '⚔ #123');
INSERT INTO node (id, code, label) VALUES(324, 'B:355', '💬 355');
INSERT INTO node (id, code, label) VALUES(325, 'GS:14w', '🚩 14w');
INSERT INTO node (id, code, label) VALUES(326, 'GS:14l', '🚩 14l');
INSERT INTO node (id, code, label) VALUES(327, 'GS:R-17', '🚩 R-17');
INSERT INTO node (id, code, label) VALUES(328, 'GS:15j', '🚩 15j');
INSERT INTO node (id, code, label) VALUES(329, 'B:078', '💬 078');
INSERT INTO node (id, code, label) VALUES(330, 'GS:11n', '🚩 11n');
INSERT INTO node (id, code, label) VALUES(331, 'GS:9i', '🚩 9i');


INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(0, 272, 189, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(1, 189, 1, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(2, 1, 208, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(3, 1, 8, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(4, 208, 204, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(5, 204, 250, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(6, 250, 141, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(7, 250, 39, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(8, 8, 207, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(9, 207, 97, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(10, 97, 103, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(11, 97, 182, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(12, 141, 227, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(13, 227, 42, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(14, 39, 324, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(15, 324, 42, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(16, 42, 219, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(17, 42, 279, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(18, 103, 304, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(19, 304, 273, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(20, 182, 71, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(21, 71, 273, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(22, 273, 36, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(23, 273, 122, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(24, 219, 145, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(25, 145, 200, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(26, 200, 29, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(27, 200, 179, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(28, 279, 281, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(29, 281, 175, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(30, 175, 315, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(31, 175, 106, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(32, 36, 119, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(33, 119, 200, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(34, 122, 111, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(35, 111, 175, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(36, 29, 319, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(37, 319, 240, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(38, 240, 32, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(39, 240, 321, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(40, 179, 232, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(41, 232, 68, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(42, 68, 32, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(43, 68, 321, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(44, 315, 112, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(45, 112, 96, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(46, 96, 262, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(47, 96, 306, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(48, 106, 102, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(49, 102, 73, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(50, 73, 262, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(51, 73, 306, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(52, 32, 12, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(53, 12, 128, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(54, 128, 109, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(55, 128, 123, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(56, 321, 84, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(57, 84, 128, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(58, 128, 158, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(59, 128, 322, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(60, 262, 12, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(61, 12, 128, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(62, 128, 110, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(63, 128, 26, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(64, 306, 84, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(65, 84, 128, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(66, 128, 79, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(67, 128, 86, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(68, 109, 98, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(69, 98, 121, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(70, 121, 202, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(71, 121, 164, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(72, 123, 24, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(73, 24, 231, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(74, 231, 202, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(75, 231, 164, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(76, 158, 98, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(77, 98, 121, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(78, 121, 193, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(79, 121, 95, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(80, 322, 24, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(81, 24, 231, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(82, 231, 193, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(83, 231, 95, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(84, 110, 98, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(85, 98, 121, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(86, 121, 276, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(87, 121, 108, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(88, 26, 24, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(89, 24, 231, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(90, 231, 276, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(91, 231, 108, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(92, 79, 98, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(93, 98, 121, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(94, 121, 92, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(95, 121, 22, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(96, 86, 24, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(97, 24, 231, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(98, 231, 92, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(99, 231, 22, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(100, 202, 223, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(101, 223, 267, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(102, 267, 247, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(103, 267, 59, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(104, 193, 223, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(105, 223, 267, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(106, 267, 289, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(107, 267, 274, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(108, 276, 223, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(109, 223, 267, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(110, 267, 331, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(111, 267, 48, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(112, 92, 223, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(113, 223, 267, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(114, 267, 81, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(115, 267, 170, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(116, 164, 260, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(117, 260, 252, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(118, 252, 69, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(119, 252, 277, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(120, 95, 260, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(121, 260, 252, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(122, 252, 70, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(123, 252, 301, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(124, 108, 260, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(125, 260, 252, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(126, 252, 195, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(127, 252, 167, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(128, 22, 260, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(129, 260, 252, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(130, 252, 184, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(131, 252, 295, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(132, 247, 38, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(133, 38, 144, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(134, 144, 46, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(135, 144, 138, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(136, 59, 19, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(137, 19, 144, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(138, 144, 137, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(139, 144, 327, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(140, 69, 210, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(141, 210, 234, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(142, 234, 41, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(143, 234, 30, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(144, 277, 124, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(145, 124, 234, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(146, 234, 3, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(147, 234, 31, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(148, 289, 38, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(149, 38, 144, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(150, 144, 120, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(151, 144, 152, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(152, 274, 19, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(153, 19, 144, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(154, 144, 284, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(155, 144, 56, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(156, 70, 210, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(157, 210, 234, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(158, 234, 220, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(159, 234, 151, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(160, 301, 124, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(161, 124, 234, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(162, 234, 254, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(163, 234, 44, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(164, 331, 38, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(165, 38, 144, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(166, 144, 43, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(167, 144, 230, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(168, 48, 19, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(169, 19, 144, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(170, 144, 62, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(171, 144, 176, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(172, 195, 210, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(173, 210, 234, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(174, 234, 90, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(175, 234, 147, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(176, 167, 124, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(177, 124, 234, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(178, 234, 246, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(179, 234, 218, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(180, 81, 38, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(181, 38, 144, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(182, 144, 213, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(183, 144, 115, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(184, 170, 19, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(185, 19, 144, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(186, 144, 248, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(187, 144, 275, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(188, 184, 210, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(189, 210, 234, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(190, 234, 239, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(191, 234, 35, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(192, 295, 124, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(193, 124, 234, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(194, 234, 21, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(195, 234, 221, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(196, 41, 329, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(197, 329, 55, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(198, 220, 329, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(199, 329, 168, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(200, 90, 329, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(201, 329, 294, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(202, 239, 329, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(203, 329, 296, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(204, 30, 291, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(205, 291, 249, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(206, 31, 291, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(207, 291, 89, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(208, 151, 291, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(209, 291, 209, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(210, 44, 291, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(211, 291, 146, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(212, 147, 291, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(213, 291, 14, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(214, 218, 291, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(215, 291, 305, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(216, 35, 291, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(217, 291, 282, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(218, 221, 291, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(219, 291, 75, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(220, 3, 299, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(221, 299, 55, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(222, 254, 299, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(223, 299, 168, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(224, 246, 299, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(225, 299, 294, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(226, 21, 299, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(227, 299, 296, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(228, 327, 203, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(229, 203, 135, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(230, 56, 203, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(231, 203, 74, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(232, 176, 203, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(233, 203, 215, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(234, 275, 203, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(235, 203, 134, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(236, 46, 40, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(237, 40, 165, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(238, 137, 40, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(239, 40, 150, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(240, 120, 40, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(241, 40, 287, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(242, 284, 40, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(243, 40, 169, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(244, 43, 40, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(245, 40, 166, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(246, 62, 40, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(247, 40, 13, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(248, 213, 40, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(249, 40, 51, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(250, 248, 40, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(251, 40, 308, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(252, 138, 78, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(253, 78, 135, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(254, 152, 78, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(255, 78, 74, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(256, 230, 78, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(257, 78, 215, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(258, 115, 78, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(259, 78, 134, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(260, 165, 191, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(261, 191, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(262, 94, 256, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(263, 94, 236, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(264, 135, 125, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(265, 125, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(266, 94, 83, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(267, 94, 285, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(268, 150, 125, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(269, 125, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(270, 94, 256, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(271, 94, 236, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(272, 55, 125, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(273, 125, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(274, 94, 256, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(275, 94, 236, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(276, 249, 125, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(277, 125, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(278, 94, 83, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(279, 94, 285, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(280, 89, 20, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(281, 20, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(282, 94, 142, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(283, 94, 33, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(284, 287, 191, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(285, 191, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(286, 94, 142, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(287, 94, 33, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(288, 169, 125, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(289, 125, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(290, 94, 142, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(291, 94, 33, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(292, 74, 226, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(293, 226, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(294, 317, 117, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(295, 317, 265, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(296, 168, 125, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(297, 125, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(298, 94, 142, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(299, 94, 33, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(300, 209, 226, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(301, 226, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(302, 317, 117, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(303, 317, 265, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(304, 146, 15, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(305, 15, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(306, 317, 117, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(307, 317, 265, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(308, 166, 191, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(309, 191, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(310, 94, 192, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(311, 94, 172, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(312, 13, 125, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(313, 125, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(314, 94, 192, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(315, 94, 172, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(316, 215, 226, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(317, 226, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(318, 317, 85, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(319, 317, 293, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(320, 294, 125, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(321, 125, 94, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(322, 94, 192, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(323, 94, 172, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(324, 14, 226, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(325, 226, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(326, 317, 85, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(327, 317, 293, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(328, 263, 15, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(329, 15, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(330, 317, 85, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(331, 317, 293, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(332, 51, 245, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(333, 245, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(334, 317, 233, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(335, 317, 330, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(336, 308, 226, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(337, 226, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(338, 317, 233, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(339, 317, 330, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(340, 134, 226, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(341, 226, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(342, 94, 66, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(343, 317, 155, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(344, 296, 226, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(345, 226, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(346, 317, 233, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(347, 317, 330, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(348, 282, 226, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(349, 226, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(350, 317, 66, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(351, 317, 155, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(352, 75, 15, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(353, 15, 317, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(354, 317, 66, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(355, 317, 155, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(356, 256, 133, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(357, 133, 244, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(358, 244, 264, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(359, 244, 320, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(360, 236, 47, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(361, 47, 244, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(362, 244, 264, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(363, 244, 320, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(364, 83, 133, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(365, 133, 244, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(366, 244, 65, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(367, 244, 217, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(368, 285, 154, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(369, 154, 244, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(370, 244, 65, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(371, 244, 217, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(372, 142, 133, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(373, 133, 244, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(374, 244, 197, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(375, 244, 101, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(376, 33, 154, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(377, 154, 244, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(378, 244, 197, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(379, 244, 101, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(380, 192, 133, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(381, 133, 244, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(382, 244, 187, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(383, 244, 6, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(384, 172, 154, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(385, 154, 244, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(386, 244, 187, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(387, 244, 6, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(388, 117, 283, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(389, 283, 312, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(390, 312, 64, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(391, 312, 127, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(392, 265, 9, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(393, 9, 312, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(394, 312, 64, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(395, 312, 127, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(396, 85, 140, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(397, 140, 180, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(398, 180, 205, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(399, 180, 309, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(400, 293, 259, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(401, 259, 180, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(402, 180, 205, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(403, 180, 309, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(404, 233, 140, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(405, 140, 180, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(406, 180, 139, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(407, 180, 229, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(408, 330, 259, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(409, 259, 180, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(410, 180, 139, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(411, 180, 229, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(412, 66, 314, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(413, 314, 180, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(414, 180, 132, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(415, 180, 303, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(416, 155, 259, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(417, 259, 180, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(418, 180, 132, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(419, 180, 303, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(420, 264, 45, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(421, 45, 171, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(422, 171, 76, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(423, 171, 235, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(424, 320, 107, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(425, 107, 87, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(426, 87, 76, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(427, 87, 235, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(428, 65, 45, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(429, 45, 171, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(430, 171, 211, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(431, 171, 292, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(432, 217, 107, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(433, 107, 87, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(434, 87, 211, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(435, 87, 292, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(436, 197, 45, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(437, 45, 171, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(438, 171, 28, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(439, 171, 174, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(440, 101, 107, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(441, 107, 87, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(442, 87, 28, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(443, 87, 174, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(444, 187, 45, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(445, 45, 171, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(446, 171, 159, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(447, 171, 278, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(448, 6, 107, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(449, 107, 87, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(450, 87, 159, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(451, 87, 278, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(452, 64, 143, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(453, 143, 323, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(454, 323, 298, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(455, 323, 216, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(456, 127, 258, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(457, 258, 178, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(458, 178, 298, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(459, 178, 216, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(460, 205, 143, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(461, 143, 323, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(462, 323, 10, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(463, 323, 206, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(464, 309, 258, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(465, 258, 178, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(466, 178, 10, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(467, 178, 206, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(468, 139, 143, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(469, 143, 323, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(470, 323, 18, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(471, 323, 82, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(472, 229, 258, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(473, 258, 178, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(474, 178, 18, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(475, 178, 82, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(476, 132, 143, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(477, 143, 323, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(478, 323, 243, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(479, 323, 63, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(480, 303, 258, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(481, 258, 178, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(482, 178, 243, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(483, 178, 63, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(484, 235, 105, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(485, 105, 288, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(486, 288, 228, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(487, 288, 17, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(488, 211, 157, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(489, 157, 288, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(490, 288, 0, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(491, 288, 5, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(492, 292, 105, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(493, 105, 288, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(494, 288, 162, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(495, 288, 93, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(496, 28, 157, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(497, 157, 288, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(498, 288, 72, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(499, 288, 27, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(500, 174, 105, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(501, 105, 288, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(502, 288, 266, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(503, 288, 58, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(504, 159, 224, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(505, 224, 131, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(506, 131, 183, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(507, 131, 326, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(508, 278, 257, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(509, 257, 131, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(510, 131, 188, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(511, 131, 67, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(512, 298, 129, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(513, 129, 177, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(514, 177, 11, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(515, 177, 316, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(516, 216, 313, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(517, 313, 177, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(518, 177, 52, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(519, 177, 297, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(520, 10, 129, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(521, 129, 177, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(522, 177, 255, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(523, 177, 190, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(524, 206, 313, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(525, 313, 177, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(526, 177, 160, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(527, 177, 114, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(528, 18, 129, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(529, 129, 177, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(530, 177, 325, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(531, 177, 237, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(532, 82, 313, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(533, 313, 177, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(534, 177, 280, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(535, 177, 173, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(536, 243, 129, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(537, 129, 177, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(538, 177, 91, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(539, 177, 136, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(540, 228, 198, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(541, 198, 318, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(542, 318, 37, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(543, 318, 153, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(544, 91, 307, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(545, 307, 57, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(546, 57, 222, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(547, 57, 50, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(548, 136, 113, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(549, 113, 100, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(550, 100, 222, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(551, 100, 50, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(552, 17, 104, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(553, 104, 88, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(554, 88, 181, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(555, 88, 153, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(556, 0, 198, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(557, 198, 318, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(558, 318, 130, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(559, 318, 25, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(560, 5, 104, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(561, 104, 88, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(562, 88, 242, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(563, 88, 25, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(564, 162, 198, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(565, 198, 318, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(566, 318, 261, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(567, 318, 23, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(568, 93, 104, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(569, 104, 88, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(570, 88, 261, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(571, 88, 23, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(572, 72, 198, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(573, 198, 318, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(574, 318, 253, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(575, 318, 53, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(576, 27, 104, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(577, 104, 88, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(578, 88, 253, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(579, 88, 53, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(580, 266, 198, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(581, 198, 318, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(582, 318, 290, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(583, 318, 328, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(584, 58, 104, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(585, 104, 88, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(586, 88, 290, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(587, 88, 328, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(588, 183, 198, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(589, 198, 318, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(590, 318, 7, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(591, 318, 163, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(592, 326, 104, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(593, 104, 88, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(594, 88, 7, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(595, 88, 163, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(596, 188, 198, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(597, 198, 318, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(598, 318, 16, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(599, 318, 251, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(600, 67, 104, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(601, 104, 88, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(602, 88, 16, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(603, 88, 251, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(604, 11, 307, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(605, 307, 57, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(606, 57, 148, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(607, 57, 199, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(608, 316, 113, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(609, 113, 100, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(610, 100, 148, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(611, 100, 199, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(612, 52, 118, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(613, 118, 57, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(614, 57, 2, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(615, 57, 241, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(616, 297, 60, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(617, 60, 100, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(618, 100, 2, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(619, 100, 241, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(620, 255, 307, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(621, 307, 57, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(622, 57, 54, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(623, 57, 196, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(624, 190, 113, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(625, 113, 100, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(626, 100, 54, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(627, 100, 196, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(628, 160, 118, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(629, 118, 57, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(630, 57, 126, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(631, 57, 4, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(632, 114, 60, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(633, 60, 100, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(634, 100, 126, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(635, 100, 4, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(636, 325, 307, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(637, 307, 57, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(638, 57, 77, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(639, 57, 310, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(640, 237, 113, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(641, 113, 100, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(642, 100, 77, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(643, 100, 310, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(644, 280, 118, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(645, 118, 57, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(646, 57, 212, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(647, 57, 300, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(648, 173, 60, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(649, 60, 100, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(650, 100, 212, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(651, 100, 300, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(652, 222, 225, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(653, 225, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(654, 80, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(655, 80, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(656, 153, 302, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(657, 302, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(658, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(659, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(660, 25, 302, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(661, 302, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(662, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(663, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(664, 261, 194, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(665, 194, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(666, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(667, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(668, 23, 270, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(669, 270, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(670, 80, 268, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(671, 80, 149, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(672, 53, 302, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(673, 302, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(674, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(675, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(676, 290, 194, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(677, 194, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(678, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(679, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(680, 328, 270, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(681, 270, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(682, 80, 268, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(683, 80, 149, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(684, 163, 302, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(685, 302, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(686, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(687, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(688, 16, 194, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(689, 194, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(690, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(691, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(692, 251, 270, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(693, 270, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(694, 80, 268, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(695, 80, 149, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(696, 148, 271, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(697, 271, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(698, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(699, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(700, 199, 269, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(701, 269, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(702, 80, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(703, 80, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(704, 2, 286, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(705, 286, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(706, 80, 268, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(707, 80, 149, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(708, 54, 271, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(709, 271, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(710, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(711, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(712, 196, 269, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(713, 269, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(714, 80, 99, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(715, 80, 99, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(716, 126, 286, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(717, 286, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(718, 80, 268, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(719, 80, 149, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(720, 77, 271, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(721, 271, 311, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(722, 311, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(723, 311, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(724, 310, 269, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(725, 269, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(726, 80, 116, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(727, 80, 156, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(728, 212, 286, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(729, 286, 80, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(730, 80, 268, 'Soviet');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(731, 80, 149, 'German');
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(732, 76, 161, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(733, 63, 185, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(734, 181, 186, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(735, 50, 49, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(736, 242, 186, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(737, 253, 186, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(738, 7, 186, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(739, 241, 238, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(740, 4, 238, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(741, 300, 238, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(742, 268, 34, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(743, 149, 201, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(744, 116, 214, NULL);
INSERT INTO edge (id, source_node_id, target_node_id, label) VALUES(745, 156, 61, NULL);